FROM node:20-bullseye

WORKDIR /src/app

# Copy only package.json / lockfile
COPY package*.json ./

# Install Linux-compatible dependencies
RUN npm ci

# Copy rest of project
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
c