FROM node:20-bullseye

WORKDIR /src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app
COPY . .

# Expose dev port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]
